config/routes.rb
Rails.application.routes.draw do
  root "couriers#index"
  resources :couriers do
    resources :packages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord
  has_many :packages

  validates :name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :courier
  validates :tracking_number, presence: true, format: /[0-9]+/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  def index
    @couriers = Courier.all
  end

  def show
    @courier = Courier.find(params[:id])
  end

  def new
    @courier = Courier.new
  end

  def create
    @courier = Courier.new(courier_params)

    if @courier.save
      #redirect_to @courier
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @courier = Courier.find(params[:id])
  end

  def update
    @courier = Courier.find(params[:id])

    if @courier.update(courier_params)
      #redirect_to @courier
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @courier = Courier.find(params[:id])
    @courier.destroy

    redirect_to root_path
  end

  private
  def courier_params
    params.require(:courier).permit(:name, :email)
  end

end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  def create
    @courier = Courier.find(params[:courier_id])
    @package = @courier.packages.create(package_params)
    redirect_to courier_path(@courier)
  end

  private
  def package_params
    params.require(:package).permit(:tracking_number, :delivery_status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/couriers/_courier_edit_form.erb
<%= form_with model: @courier do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @courier.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_area :email %>
    <% @courier.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/couriers/edit.html.erb
<h1>Edit Courier account</h1>

<%= render "courier_edit_form", courier: @courier %>

app/views/couriers/index.html.erb
<h1>Couriers</h1>

<ul>
  <%@couriers.each do |courier| %>
    <li>
      <%= link_to courier.name, courier %> | <%= link_to "Edit", edit_courier_path(courier) %>
    </li>
  <% end %>
</ul>

<%= link_to "New Courier", new_courier_path %>

app/views/couriers/new.html.erb
<h1>New Courier</h1>

<%= render "courier_edit_form", courier: @courier %>

app/views/couriers/show.html.erb
<h2>Courier account</h2>
<p><%= link_to "Edit", edit_courier_path(@courier) %> | <%= link_to "Home", root_path %></p>
<p>Name:<%= @courier.name %> </p>
<p>E-mail:<%= @courier.email %></p>

<h2><%= @courier.name %> packages</h2>
<table>
  <thead>
  <tr>
    <th>Tracking number</th>
    <th>Delivery status</th>
  </tr>
  </thead>
  <tbody>
  <%= render @courier.packages %>
  </tbody>
</table>

<h2>Add a NEW package to courier <%= @courier.name %>:</h2>
<%= form_with model: [ @courier, @courier.packages.build ] do |form| %>
  <p>
    <%= form.label :tracking_number %><br>
    <%= form.text_field :tracking_number %>
  </p>
  <p>
    <%= form.label :delivery_status %><br>
    <%= form.check_box :delivery_status %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>